### PR TITLE
Huge dependency update

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by ramilexe** [comment]
`make build` on that branch show follow errors:

```make build
rm -rf build/ethermint
go build \
                --ldflags "-X github.com/tendermint/ethermint/version.GitCommit=`git rev-parse HEAD`"  -o build/ethermint ./cmd/ethermint/
vendor/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:34:2: cannot find package "github.com/edsrzf/mmap-go" in any of:
        /srv/ethermint/src/github.com/tendermint/ethermint/vendor/github.com/edsrzf/mmap-go (vendor tree)
        /usr/local/go/src/github.com/edsrzf/mmap-go (from $GOROOT)
        /srv/ethermint/src/github.com/edsrzf/mmap-go (from $GOPATH)
vendor/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:32:2: cannot find package "github.com/karalabe/hid" in any of:
       /srv/ethermint/src/github.com/tendermint/ethermint/vendor/github.com/karalabe/hid (vendor tree)
        /usr/local/go/src/github.com/karalabe/hid (from $GOROOT)
        /srv/ethermint/src/github.com/karalabe/hid (from $GOPATH)
```

**Comment by adrianbrink** [comment]
Interesting, I don't get a build error.

**Comment by adrianbrink** [comment]
Have you run ```make get_vendor_deps``` and ```make get_deps```. Generally it is more stable to use the makefile instead of running ```go build ...```

**Comment by ramilexe** [comment]
I run `make get_vendor_deps` and `make build`. Why we need `make get_deps`? Shouldn't we manage all dependency via `glide`? 

`make get_deps` fix my issue

**Pull request merged**
