### PR TITLE
fix metalinter warnings and add to CI

### LINKED ISSUE #196: Make linting checks part of the development process
We should strive to only have very clean code for ethermint.

We currently have two separate linters `gometalinter` and `megacheck`.

As such this issue is three fold:
1. Add an explanation of how to install all our linters.
2. Update the Makefile so that the linters get run on every test and build run.
3. Update the CI build steps to fail on linting errors.

### PR DESCRIPTION
**Pull request by zramsay**
- closes #196 
- will be documented in coding repo and eventually standardized across the stack

### CODE REVIEW

**Comment by adrianbrink** [comment]
I've added your remote and tried to push to it directly. But I cannot force push to it, which I have to do for the rebasing. I think as long as it's only three people developing these features, it would be great if we can all have branches on the main repo, because I always end up taking these PRs, moving them onto the main repo and then pushing them.

@odeke-em fyi

**Comment by odeke-em** [comment]
Roger that @adrianbrink, thanks for the suggestion. I thought about that too when I saw that you had to copy a bunch of commits to a branch on the main repo.

**Comment by adrianbrink** [comment]
Do you have access to create branches on Ethermint?

**Comment by adrianbrink** [comment]
I'm closing this in favour of #298 . In the future please create branches directly on the main repo, because otherwise, we can't collaborate on features.

**Comment by zramsay** [comment]
screenshot from 2017-08-29 12-23-09
we can just check ^ that box on the right hand side but yeah, sure

**Pull request closed without merging**
