### PR TITLE
Fix build failure on Mac OS

### PR DESCRIPTION
**Pull request by melekes**
Refs #357

I also changed a bunch of other stuff. Feel free to critique, so we (me especially) get a better understanding of go linker and other building params.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f3bcdd212b40fcfc7001c8ad045c1df1d0014a87
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 47dfdda9fe4925fc0c0dc9c9ac98a12e6dd2a2dd
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 0cfbcb927a87941e1428dc6a921f5940a305044f
  * Your commit message body contains a line that is longer than 72 characters

Line length is maximum 72 characters.

Guidelines are available at https://github.com/tendermint/ethermint

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f3bcdd212b40fcfc7001c8ad045c1df1d0014a87
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 47dfdda9fe4925fc0c0dc9c9ac98a12e6dd2a2dd
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 0cfbcb927a87941e1428dc6a921f5940a305044f
  * Your commit message body contains a line that is longer than 72 characters

Line length is maximum 72 characters.

Guidelines are available at https://github.com/tendermint/ethermint

---
This message was auto-generated by https://gitcop.com

**Comment by adrianbrink** [comment]
Why do we explicitly have to turn on CGO and what fixes the build error?

**Comment by melekes** [comment]
> Why do we explicitly have to turn on CGO and what fixes the build error?

1) because go-ethereum has a small C library as a dep
2) explicit export (CGO_ENABLED=1) fixes the build error

**Comment by adrianbrink** [comment]
Lol, I would call this a breaking change in go-lang.

**Comment by adrianbrink** [comment]
Can you fix the commit messages and then this is good :-)

**Review by adrianbrink — APPROVED** [review]

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e06bd22f214f6b5b10309d1e2bd9da86cae3a8ed
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: af3b629bf333ebd9f3deb24c2b9f381f82a7cb1a
  * Your commit message body contains a line that is longer than 72 characters

Line length is maximum 72 characters.

Guidelines are available at https://github.com/tendermint/ethermint

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
