### PR TITLE
Update CONTRIBUTING.md with explanation on feature branches

### PR DESCRIPTION
**Pull request by adrianbrink**

### CODE REVIEW

**Comment by odeke-em** [comment]
@adrianbrink what's the rationale behind this `feature/XXX` nomenclature? How about bug fixes, doc updates etc? I think we'll probably get those more than even features.

**Comment by adrianbrink** [comment]
I think we should follow [git-flow](http://nvie.com/posts/a-successful-git-branching-model/). That's where `feature` comes from.

I can be convinced to change this though :-)

**Comment by greg-szabo** [comment]
feature/XXX and similar is used in Atlassian extensively too. Since it's integrated with JIRA, where you specifically open feature, bug or other requests, it makes sense to take that information to the branch opened. In Atlassian the keywords are feature, release, hotfix and custom. (I think.)

My 2 cents:

1. I propose we come up with our own prefixes and start using them to make it easier to identify the goals of a branch. (If we can lets keep to standards but I think there's no "doc/" prefix in any standards.)
1. Also, as mentioned on Slack, let's open a GitHub issue with each branch opened. The issue can be closed when the branch is deleted. (after merge or decline)
1. I second Adrian's proposal to start using git-flow as our official way of managing the repositories. I propose we have a meeting where someone with experience in git-flow goes through an example so it's easier to understand. (I know everyone can read documentation but it's much quicker to discuss it.)
1. I propose that any PR open for more than 2 weeks should be declined (and the author notified). This takes cares of long-running and abandoned PRs: if it's abandoned we shouldn't keep it around. If it's worked on, then most probably it wasn't ready for merging when it was opened. It can always be reopened at a later date when it's more mature.

**Comment by zramsay** [comment]
a big yes on point 4, and agree on all the other points. Let's move this discussion to https://github.com/tendermint/coding/issues/17 / in that repo somewhere since it applies broadly

**Pull request merged**
