### PR TITLE
Docs for connecting to the testnet

### PR DESCRIPTION
**Pull request by zramsay**
#179

### CODE REVIEW

**Comment by adrianbrink** [comment]
@zramsay Could you make an account [here](https://readthedocs.org/) so that I can add you as a maintainer for the documentation. 

Then can you update this PR so that it works with the documentation that is hosted from the docs folder.

**Review by adrianbrink — CHANGES_REQUESTED** [review]
@zramsay Could you make an account [here](https://readthedocs.org/) so that I can add you as a maintainer for the documentation. 

Then can you update this PR so that it works with the documentation that is hosted from the docs folder.

**Comment by zramsay** [comment]
same username on RTD

**Comment by adrianbrink** [comment]
Added you

**Comment by zramsay** [comment]
done. also added `docs/architecture/ibc.md` from a lone commit on a stale branch (came from another repo)

**Review by adrianbrink — APPROVED** [review]

**Pull request merged**
